chrome.extension.sendMessage({ cmd:'getElementInfo' }, elementInfo => {
	if (elementInfo) {
		beginCreationOfNewAction(elementInfo);
	}
});

const q = document.querySelector;

function beginCreationOfNewAction(elementInfo) {
	if (elementInfo) {
		q('.targetExtendedSelector').value = elementInfo;
		const t = elementInfo[0];
		q('.targetSelector').value = t.tagName
			+ (t.id
				? '#' + t.id
				: '')
			+ (t.className
				? t.className.split(' ').map(x => '.' + x).join('')
				: '');
		q('.targetSelector').disabled = true;
	}

	q('.targetAutoGenerated')
}